before_install: cd xelp-app
language: node_js
node_js:
  - 8.4.0
before_script:
- npm run build:prod
- psql -c 'create database xelp;' -U postgres
- knex migrate:latest
script: node ./build/server/index.js & npm run test